### ISSUE TITLE
Request new features

### ISSUE THREAD

**Issue by xsswang** [milan102/Random-Mouse-Clicker#2]
Hi,
This is a great app which functions well. If possible, please add the following features:

1) a STOP button beside the START button
2) allow user to define combination keys, instead of fixed "CTRL+WIN+ESC".

Thanks for the great work.

**Comment by milanify** [comment]
Thank you for your suggestions! I will add these features in the next release.

**Comment by milanify** [comment]
Also sorry for not responding sooner, I fixed my notification settings.

**Comment by milanify** [comment]
Added a user defined shortcut to start/stop the program

Added a user defined shortcut to exit the program

New release has been uploaded
