### ISSUE TITLE
Feature Request - Double Click

### ISSUE THREAD

**Issue by Deeraccoon** [milan102/Random-Mouse-Clicker#3]
Hi, great tool, I was wondering if it would be possible to add an option for double click also?

**Comment by milanify** [comment]
Thank you for your request, I will add this feature in the next release.

**Comment by milanify** [comment]
Also sorry for not responding sooner, I fixed my notification settings.

**Comment by milanify** [comment]
Added a user defined setting to define the number of clicks to perform each time. For example, if you set this to 2, then it will do double clicks each time.

New release has been uploaded
