### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Fragnstein** [milan102/Random-Mouse-Clicker#5]
Hi, love the program and it works very well! Some features I'd love to see is a function to define multiple fixed areas on the screen for it to click, similar to AMC (https://sourceforge.net/projects/auto-mouse-clicker-amc/). Unfortunately, AMC is 32bit and I can't get it to work on my 64bit system. That and a user defined hotkey to pause/play would be awesome. Thanks for your hard work!

**Comment by milanify** [comment]
Definitely will add pause/play in the next release. 

For the defining multiple fixed areas, I'll look into that. I have to think of the GUI and how it would fit cleanly inside.

**Comment by milanify** [comment]
Added a user defined shortcut to start/stop the program

Added a user defined shortcut to exit the program

Sorry, could not add the functionality to define multiple fixed areas.

New release has been uploaded
